---

replicaCount: 1

image:
  repository: lobsterdore/release-dash
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

releaseDash:
  githubChangelogFetchTimerSecond: 60
  githubPatKey: github_pat
  githubRepoFetchTimerSecond: 600
  secretsName: release-dash

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
