---

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

fullnameOverride: ""

image:
  repository: lobsterdore/release-dash
  pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podSecurityContext: {}

releaseDash:
  githubChangelogFetchTimerSecond: 60
  githubPatKey: github_pat
  githubRepoFetchTimerSecond: 600
  secretsName: release-dash

replicaCount: 1

resources: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""

tolerations: []
